server:
  port: 8081
  servlet:
    context-path: /blogs

# Swagger
info:
  app:
    name: Blog Posts
    description: Backend Layer Blog Posts
    version: 1.0

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: heapdump,threaddump,info,metrics,health
  server:
    port: 8082

# Keycloak
keycloak:
  auth-server-url: http://localhost:8083/auth
  realm: blogsrealm
  client-id: blogsapp
  admin-username: rest-admin
  admin-password: admin
  pool-size: 10

# Security
security:
  basic:
    enabled: false

# Database
spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/blogsrealm
          jwk-set-uri: http://localhost:8083/auth/realms/blogsrealm/protocol/openid-connect/certs


